name: CI - Test Convert Utility

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
        
    - name: Set up build tools
      run: sudo apt-get install build-essential

    - name: Build Convert Utility
      run: make

    - name: Run Tests
      run: ./test_script > test_results.txt
        
    - name: Upload Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Test Results
        path: ./test_results.txt
